### ISSUE TITLE
Using custom rendering, where to start?

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/identity-map#1]
Hi,

I plan to create some tree-style dependency view for Part BOMs. The queries should not be a problem, but I really have trouble to understand how to use external code for the rendering.

Is there a difference between the files d3.js and d3.min.js? And where does these files actually come from? I searched through the corresponding pages from Mike Bostock but got lost very quickly.

Is the used rendering approach of this project comparable to this project from a technical point of view?
http://community.aras.com/en/rendering-bill-material-graph-using-cytoscape-js/

I have heard that some kind of graphic visualization is included in one of the next Aras service packs, But maybe there is a suitable solution available that we can apply earlier.

Maybe you have some tips on how to start here the easiest way? Thanks in advance!

**Comment by EliJDonahue** [comment]
Hi Angela,

The d3.min.js file is a "[minified](https://en.wikipedia.org/wiki/Minification_(programming))" version of the d3.js file. The d3.js file is more human-readable and the d3.min.js file has whitespace and unnecessary characters removed. The content is the same in both files and the browser understands them both the same way.

The technical approach of this project is indeed similar to the Cytoscape project you referenced. The primary difference is the visualization library used. 

Graph visualization as a platform service is coming in a future service pack. ([See the roadmap for specifics](https://www.aras.com/plm-roadmap/).) It will use Query Builder as a data source, so I would recommend following the approach outlined in this project. You can build your query and a custom graph for immediate use now, and then just add the built-in graph visualization later. 

There are a lot of samples out there for building tree diagrams with d3. Here are a couple:

- http://bl.ocks.org/d3noob/8326869
- http://bl.ocks.org/d3noob/8375092

If you prefer to use Cytoscape, you can always modify the other project to use Query Builder as a data source. There are also other graphing libraries that can produce tree diagrams. I've used [Vis.js](http://visjs.org/) for similar projects.

Eli

**Comment by AngelaIp** [comment]
Hi Eli,

thanks for the detailed explanation! Right now I think the next service pack is faster than me. 
But it´s always helpful to know about the technical background!

Angela
