### ISSUE TITLE
Use Query Definition for AML based Reports

### ISSUE THREAD

**Issue by AngelaIp** [ArasLabs/identity-map#2]
Hi Eli,

I wonder if it´s possible to use the Query Definition for AML based Reports (XSLT, Excel, PDF)?

Some time ago I found this piece of code from your colleague Yoann:
https://gist.github.com/YoannArasLab/f426a70affca0bfe0508abaa8f0c1656

I haven´t tested this one yet, but maybe it´s be possible to replace the AML part in this code with a link to the query definition?

Best regards!
Angela

**Comment by EliJDonahue** [comment]
Great suggestion, Angela! I hadn’t thought of that use case. You certainly could use a query definition to pull the data for a report. Just execute the QD in a method on the report, and then write your XSLT to handle the result.

**Comment by AngelaIp** [comment]
Hi Eli,

I am not sure if I read the Innovator 12 documentation correct - but was this topic finally realized in Innovator 12?

Angela

**Comment by EliJDonahue** [comment]
Hi Angela,

This functionality isn't an OOTB configuration in Innovator 12.0, but it's still possible to use a Query Definition as the data source for a report using the approach I mentioned earlier in the thread.

>You certainly could use a query definition to pull the data for a report. Just execute the QD in a method on the report, and then write your XSLT to handle the result.

Eli
